### PR TITLE
add config for code coverage

### PR DESCRIPTION
**Pull request by viraja1**
add config for code coverage

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by ranvijayj** [comment]
retest this please

**Comment by prathamghadge** [comment]
retest this please

**Comment by prathamghadge** [comment]
retest this please

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
