### PR TITLE
(adhoc)(platform-support) Add logs for debugging the entity detection issue for NSDC

### PR DESCRIPTION
**Pull request by haptikrajasashtikar**
## JIRA Ticket Number

JIRA TICKET: https://hello-haptik.atlassian.net/browse/BB-11092

## Description of change
- Add logger to check the request data and the result of ES queries

## Checklist (OPTIONAL):

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Review by rootAvish — APPROVED** [review]

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by rootAvish — APPROVED** [review]

**Pull request merged**
