### PR TITLE
Develop to Master - June 18, 2019

### PR DESCRIPTION
**Pull request by chiragjn**
@viraja1 add config for code coverage
@amansrivastava17 added bulk ner call for date, time, number and number range
@chiragjn Fix scale search and add test cases for all scales of budgets
@prik2693 add support for phone number detection on bulk messages

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
