### PR TITLE
Release 2019-03-20 07:42:41 +0000

### PR DESCRIPTION
**Pull request by ranvijayj**
- [x] #188 Add a code style guideline document @chiragjn
- [x] #200 Updated api documentation for Ner V2  @amansrivastava17
- [x] #211 Name detection - Format Structured value correctly when detection fails @chiragjn
- [x] #215 fixing search query @josecannete
- [x] #218 Fix some date patterns and add support for more range patterns @chiragjn
- [x] #219 Add airport code CSV @ranvijayj
- [x] #221 Allow detection of person name written in latin script for hindi bots @ashutoshsingh0223
- [x] #222 Add mergeability and release drafter @ranvijayj
- [x] #224 Contribution guidelines overview @krupalmodi18
- [x] #225 update units.csv @viraja1
- [x] #226 add numerals constant data fix @viraja1
- [x] #229 Added new url call to read unique values for text entity @amansrivastava17

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
