### PR TITLE
Add telugu data date

### PR DESCRIPTION
**Pull request by Ruthvik-Reddy-Haptik**
Folder for telugu

### CODE REVIEW

**Comment by srajdev** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by haptik-deployment** [comment]
Can one of the admins verify this patch?

**Comment by srajdev** [comment]
Could not review pull request. It may be too large, or contain no reviewable changes.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by ranvijayj** [comment]
ok to test

**Pull request closed without merging**
