### PR TITLE
added telugu date and number data

### PR DESCRIPTION
**Pull request by Ruthvik-Reddy-Haptik**
Added date and number data for Telugu.

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
Can one of the admins verify this patch?

**Comment by chiragjn** [comment]
retest this please

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by amansrivastava17** [comment]
retest this please

**Comment by amansrivastava17** [comment]
retest this please

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request closed without merging**
