### PR TITLE
fix(logging): set up loggers using django's  `settings.LOGGING` to be able to log request tracebacks

### PR DESCRIPTION
**Pull request by chiragjn**
## JIRA Ticket Number

JIRA TICKET: ML-2755

## Description of change
Because `settings.DEBUG = False` we can't rely on uwsgi to give us any tracebacks in logs because django won't propagate it. It is better to attach our handler to `django.request`

## Checklist (OPTIONAL):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by rootAvish — APPROVED** [review]

**Comment by rootAvish** [comment]
You need to rebase I think, but otherwise thanks a lot for the fix. I'll try this on my branch and see what error that particular issue produces.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by rootAvish — APPROVED** [review]

**Pull request merged**
