### PR TITLE
Bug fixes for v2/number, v2/number_range, v2/time

### PR DESCRIPTION
**Pull request by chiragjn**
## JIRA Ticket Number

JIRA TICKET:  BB-3339, ML-2316, ML-766, ML-2289, ML-2325

## Description of change
- Fixes IndexError for person_name detection and makes the bot message check lenient for unsupported languages
- Fixes false positive number detection in time detection. Demand a separator for such cases e.g. fail on "145", e.g. "1:45"
- Fixes number and number range detectors to require the detected spans to have sensible boundaries instead of being any substrings
- Uncomments and fixes all previously failing tests and updates tests for new changes
---
- Minor refactor to `ner_v2/api.py`
- Bumps sentry-sdk, django-nose and coverage
- Changes formatter on logger and removes unused logger
- Fixes coverage reports
- Drops unused html, css and js files
---

Closes: #372 
Closes: #397
Closes: #399
Closes: #400
Closes: #401
Closes: #402
Closes: #403
Closes: #404
Closes: #410
Closes: #411

## Checklist (OPTIONAL):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS FAILED... Please resolve issues

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Review by tanaya-b — APPROVED** [review]

**Pull request merged**
