### PR TITLE
Removed unused crf code

### PR DESCRIPTION
**Pull request by chiragjn**
## JIRA Ticket Number

JIRA TICKET: ML-1504

## Description of change
Remove older CRF models code that is not being used

## Checklist (OPTIONAL):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by SinghDivneet** [comment]
Retest this please

**Comment by ranvijayj** [comment]
Retest this please

**Comment by ranvijayj** [comment]
Retest this please

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by amansrivastava17 — APPROVED** [review]

**Pull request merged**
