### PR TITLE
Capture time taken for internal transfer

### PR DESCRIPTION
**Pull request by harjinder7**
## JIRA Ticket Number

JIRA TICKET: ML-3380

## Description of change
logging time taken for internal transfer

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Review by naseem-shaik — APPROVED** [review]
LGTM

**Review by HiteshC6595 — APPROVED** [review]
Tested, it is working fine

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
