### PR TITLE
TextDetector - Reset internal state

### PR DESCRIPTION
**Pull request by chiragjn**
TextDetector - Reset internal state before starting any detection to ensure original_text is set correctly every call

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
