### PR TITLE
Redo phonenumber with libphonenumber

### PR DESCRIPTION
**Pull request by amansrivastava17**
Redo phone number with libphonenumber. Changed output from phone_number to value to be consistent with other detector outputs.

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
