### PR TITLE
Fix issue in single char scale for number detection

### PR DESCRIPTION
**Pull request by amansrivastava17**
**Issue** - In number detection single scale char like `m` is being detected as 1 million
**Solution** - not considering scale word with len = 1 while converting number words to number

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
