### PR TITLE
Remove SECRET_KEY from settings and move to ENV

### PR DESCRIPTION
**Pull request by ranvijayj**
Remove SECRET_KEY from settings and move to ENV
Value to will be retrieved from ENVKEY or .env for dev
ADHOC - Security

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by ranvijayj** [comment]
retest this please

**Comment by ranvijayj** [comment]
retest this please

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
