### PR TITLE
added one more word for next

### PR DESCRIPTION
**Pull request by shantanuo**
added a word पुढल्या means next

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
Can one of the admins verify this patch?

**Comment by ranvijayj** [comment]
retest this please

**Comment by ranvijayj** [comment]
ok to test

**Comment by shantanuo** [comment]
There is a better way to convert marathi text to numbers using hunspell.
https://github.com/shantanuo/spell_check/blob/master/marthi_numbers_to_text.ipynb

**Pull request merged**
