### PR TITLE
Hotfix: Temporary increase in maximum entities allowed

### PR DESCRIPTION
**Pull request by tanaya-b**
## JIRA Ticket Number

JIRA TICKET: On-call fix

## Description of change
Temporary increase to 160

## Checklist (OPTIONAL):

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Review by rootAvish — DISMISSED** [review]

**Review by krupalmodi18 — DISMISSED** [review]

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by krupalmodi18 — APPROVED** [review]

**Review by rootAvish — APPROVED** [review]

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
