### PR TITLE
NameDetector - Standalone name detection restriction

### PR DESCRIPTION
**Pull request by ashutoshsingh0223**
NameDetector - Standalone name will only be detected if bot_mesaage is non null

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by chiragjn** [comment]
retest this please

**Comment by haptik-deployment** [comment]
UNIT TESTS FAILED... Please resolve issues

**Pull request merged**
