### PR TITLE
Move log line from .info to .debug for less spam

### PR DESCRIPTION
**Pull request by chiragjn**
Just reduces log spam

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Review by tanaya-b — APPROVED** [review]

**Comment by chiragjn** [comment]
retest this please

**Comment by chiragjn** [comment]
retest this please

**Comment by minion96** [comment]
retest this please

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
