### PR TITLE
Develop to Master Sync

### PR DESCRIPTION
**Pull request by ankur09011**
PRs: #388 , #390

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Review by chiragjn — APPROVED** [review]

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by chiragjn — APPROVED** [review]

**Pull request merged**
