### PR TITLE
Added new url call to read unique values for text entity

### PR DESCRIPTION
**Pull request by amansrivastava17**
Create a new API call to get unique values for text entity.

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Pull request merged**
