### PR TITLE
ML-3174 : Update log level on the handled overflow exception

### PR DESCRIPTION
**Pull request by harjinder7**
## JIRA Ticket Number

JIRA TICKET: ML-3174

## Description of change
Logging warning and added unit test case

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by naseem-shaik — APPROVED** [review]
LGTM. Please ensure the new test case being added is working fine.

**Review by tanaya-b — APPROVED** [review]

**Review by sanoopnair — APPROVED** [review]

**Pull request merged**
