### PR TITLE
Add variations in marathi date and time

### PR DESCRIPTION
**Pull request by ameya3012**

### CODE REVIEW

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by haptik-deployment** [comment]
Can one of the admins verify this patch?

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by srajdev** [comment]
:+1: No lint errors found.

**Comment by ranvijayj** [comment]
ok to test

**Comment by ranvijayj** [comment]
retest this please

**Pull request closed without merging**
