### PR TITLE
adding setup files in seperate folder

### PR DESCRIPTION
**Pull request by harjinder7**
## JIRA Ticket Number

JIRA TICKET: ML-3625

## Description of change
Have added file for easier dev setup.

### CODE REVIEW

**Comment by haptik-deployment** [comment]
:+1: No lint errors found.

**Comment by harjinder7** [comment]
Entity Test suite : [output](https://bot-testing-data.s3.amazonaws.com/ML_Testing_Tool/development/entity_testing/output-devharjinder7-2023-05-25T13%3A44%3A40.124668%2B05%3A30.csv) .

Unit test case: passed (image attached)

image

**Comment by haptik-deployment** [comment]
UNIT TESTS HAVE PASSED... Good To Merge

**Review by HiteshC6595 — APPROVED** [review]
Unit test ran for these changes along regression suite and both are got passed successfully hence approving the PR

**Pull request merged**
